
# Update this file after adding/removing/renaming a target by running
# `make list-targets BROKEN=1 | ./contrib/actions/generate-actions.py > ./.github/workflows/build-gluon.yml`

name: Build Gluon
on:
  workflow_dispatch:
  push:
    branches:
      - nightly
    paths:
      - "modules"
      - "Makefile"
      - "scripts/**"
      - "package/**"
      - "patches/**"
      - "targets/**"
      - ".github/workflows/build-gluon.yml"
      - "domains/**"
      - "site.conf"
      - "site.mk"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "modules"
      - "Makefile"
      - "scripts/**"
      - "package/**"
      - "patches/**"
      - "targets/**"
      - ".github/workflows/build-gluon.yml"
      - "domains/**"
      - "site.conf"
      - "site.mk"
jobs:
  build_firmware:
    strategy:
      fail-fast: false
      matrix:
        target: [ar71xx-generic, ar71xx-tiny, ar71xx-nand, ath79-generic, brcm2708-bcm2708, brcm2708-bcm2709, ipq40xx-generic, ipq806x-generic, lantiq-xrx200, lantiq-xway, mpc85xx-generic, mpc85xx-p1020, ramips-mt7620, ramips-mt7621, ramips-mt76x8, ramips-rt305x, sunxi-cortexa7, x86-generic, x86-geode, x86-legacy, x86-64, ar71xx-mikrotik, brcm2708-bcm2710, mvebu-cortexa9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Permissions
        run: chmod +x contrib/actions/run-build.sh
      - name: Build
        run: contrib/actions/run-build.sh ${{ matrix.target }}
      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_logs
          path: openwrt/logs
      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_output
          path: output
