name: Build ffef firmware
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch?'
        required: true
        default: 'nightly'
jobs:
  Configcheck:
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    runs-on: ubuntu-20.04
    steps:
      - name: Auschecken
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive
      - name: Konfigcheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
          files: site.conf
          args: --config ./gluon/.luacheckrc
      - name: Buildmatrix
        id: setmatrix
        run: |
          matrix=$( ln -s ../ gluon/site; cd gluon; make -s list-targets BROKEN=1 |  /bin/sed 's/$/"}/' |   /bin/sed 's/^/{"target":"/' | /bin/sed ':a;N;$!ba;s/\n/,/g' )
          echo "matrix={\"include\":[$(echo $matrix)]}" >> $GITHUB_OUTPUT
  build_firmware:
    needs: Configcheck
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.Configcheck.outputs.matrix) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Auschecken
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive
      - name: Permissions
        run: chmod +x contrib/actions/run-build.sh contrib/actions/install-dependencies.sh
      - name: Install Dependencies
        run: sudo contrib/actions/install-dependencies.sh
      - name: Build
        run: contrib/actions/run-build.sh ${{ matrix.target }}
        working-directory: ./gluon
      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}_logs
          path: logs
      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}_output
          path: gluon/output
      - name: upload
        env:
          SSH_KEY: ${{ secrets.GITSYNC_PRIVATE_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SSH_KEY}"
          rsync -avz '-e ssh -o StrictHostKeyChecking=no -p2215' gluon/output/ gitsync@map.erfurt.freifunk.net:/hotfolder/${{ github.event.inputs.branch }}/
