name: Build Gluon
on:
  workflow_dispatch:
  push:
    branches:
      - nightly
    paths:
      - ".github/workflows/build-gluon.yml"
      - "domains/**"
      - "site.conf"
      - "site.mk"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/build-gluon.yml"
      - "domains/**"
      - "site.conf"
      - "site.mk"
jobs:
  Configcheck:
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    runs-on: ubuntu-20.04
    steps:
      - name: Auschecken
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
      - name: Konfigcheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
          files: site.conf
          args: --config ./gluon/.luacheckrc
      - name: Buildmatrix
        id: setmatrix
        run: |
          ln -s ../ site
          matrix=$( make -s list-targets BROKEN=1 | /bin/sed 's/$/"}/' | /bin/sed 's/^/{"target":"/' | /bin/sed ':a;N;$!ba;s/\n/,/g' )
          echo "Targets: $matrix"
          echo "matrix={\"include\":[$(echo $matrix)]}" >> $GITHUB_OUTPUT
        working-directory: gluon
  build_firmware:
    needs: Configcheck
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.Configcheck.outputs.matrix) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Auschecken
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
      - name: Permissions
        run: chmod +x contrib/actions/run-build.sh contrib/actions/install-dependencies.sh
      - name: Install Dependencies
        run: sudo contrib/actions/install-dependencies.sh
      - name: Build
        run: |
          mkdir output logs
          ln -s ../ site
          ../contrib/actions/run-build.sh ${{ matrix.target }} -j3
        working-directory: gluon
      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}_logs
          path: gluon/logs
      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}_output
          path: gluon/output
