
name: build-manual 
on:
  workflow_dispatch:
   inputs:
      branch:
        description: 'Welchen Branch'     
        required: true
        default: 'nightly'
jobs:
  Configcheck:
     outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
     runs-on: ubuntu-latest
     steps:
      - name: Auschecken
        uses: actions/checkout@v2.3.4
        with:
            ref: ${{ github.event.inputs.branch }}
            submodules: recursive
      - name: spellcheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
            files: site.conf
            args: --config ./gluon/.luacheckrc         
      - name: Buildmatrix
        id: setmatrix
        run: | 
         matrix=$( ln -s ../ gluon/site; cd gluon; make -s list-targets BROKEN=1  |  /bin/sed 's/$/"/' |   /bin/sed 's/^/"/' | /bin/sed ':a;N;$!ba;s/\n/,/g' )
         echo ::set-output name=matrix::{\"include\":$(echo $matrix)}\"
  check_target:
    needs: Configcheck
    runs-on: ubuntu-latest       
    steps:
      - run: echo ${{ fromJson(needs.Configcheck.outputs.matrix )}}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
           
   
      
  build_firmware:
    needs: Configcheck
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.Configcheck.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Auschecken
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive
      - name: Permissions
        run: chmod +x contrib/actions/run-build.sh contrib/actions/install-dependencies.sh
      - name: Install Dependencies
        run: sudo contrib/actions/install-dependencies.sh
      - name: Build
        run: contrib/actions/run-build.sh ${{ matrix.target }}
      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_logs
          path: logs
      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_output
          path: gluon/output
