name: Build ffef firmware

on:
  workflow_dispatch:
   inputs:
      branch:
        description: 'Which branch?'
        required: true
        default: 'nightly'
jobs:
  Configcheck:
     outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
     runs-on: ubuntu-latest
     steps:
      - name: Auschecken
        uses: actions/checkout@v2.3.4
        with:
            ref: ${{ github.event.inputs.branch }}
            submodules: recursive
      - name: spellcheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
            files: site.conf
            args: --config ./gluon/.luacheckrc         
      - name: Buildmatrix
        id: setmatrix
        run: | 
         matrix=$( ln -s ../ gluon/site; cd gluon; make -s list-targets BROKEN=1 |  /bin/sed 's/$/"}/' |   /bin/sed 's/^/{"target":"/' | /bin/sed ':a;N;$!ba;s/\n/,/g' )
         echo ::set-output name=matrix::{\"include\":[$(echo $matrix)]}
  build_firmware:
    needs: Configcheck
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.Configcheck.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Auschecken
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive
      - name: Permissions
        run: chmod +x contrib/actions/run-build.sh contrib/actions/install-dependencies.sh
      - name: Install Dependencies
        run: sudo contrib/actions/install-dependencies.sh
      - name: Build
        run: contrib/actions/run-build.sh ${{ matrix.target }}
      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_logs
          path: logs
      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_output
          path: gluon/output
      - name: upload
        env:
         SSH_KEY: ${{ secrets.GITSYNC_PRIVATE_KEY }}
        run: |
         eval "$(ssh-agent -s)"
         ssh-add - <<< "${SSH_KEY}"
         rsync -avz '-e ssh -o StrictHostKeyChecking=no -p2215' gluon/output/ gitsync@map.erfurt.freifunk.net:/hotfolder/${{ github.event.inputs.branch }}/

